# Generated by Django 2.2.5 on 2019-09-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_programas', to='instituciones.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_inscritos', to='instituciones.Institucion')),
                ('programas', models.ManyToManyField(to='instituciones.Programa')),
            ],
        ),
    ]
